export { Step1_BasicProfile } from './Step1_BasicProfile';
export { Step2_PhysicalInfo } from './Step2_PhysicalInfo';
export { Step3_SportType } from './Step3_SportType';
export { Step4_ExperienceLevel } from './Step4_ExperienceLevel';
export { Step5_BranchSelection } from './Step5_BranchSelection';
export { Step6_SubscriptionPlan } from './Step6_SubscriptionPlan';
export { Step7_CoachSelection } from './Step7_CoachSelection';
export { Step8_ReviewPayment } from './Step8_ReviewPayment';
export { RegistrationSuccess } from './RegistrationSuccess';
